### ISSUE TITLE
yolov5哪个版本

### ISSUE THREAD

**Issue by teacher1314** [guojianyang/cv-detect-robot#15]
这个pt模型是用哪个版本训练的，我试了v5.0和v3.0都不行。V5可以转wts,但是engine出问题，V3都转不了wts
Traceback (most recent call last):
  File "gen_wts.py", line 8, in <module>
    model = torch.load('weights/number_v5s.pt', map_location=device)['model'].float()  # load to FP32
  File "/home/lpx/.local/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/lpx/.local/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/lpx/.local/lib/python3.8/site-packages/torch/serialization.py", line 1124, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'C3' on <module 'models.common' from '/home/lpx/ros/yolov5v3.0/src/yolov5/models/common.py'>

**Comment by teacher1314** [comment]
通过自己的模型，使用V3.0版本成功跑通，jetson nano 10帧
